"""Add delivery_status to Sale

Revision ID: 0a8e85d4c598
Revises: c084bb850ba0
Create Date: 2025-12-28 17:05:45.941907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8e85d4c598'
down_revision = 'c084bb850ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_recipient_read', ['recipient_id', 'is_read'], unique=False)
        batch_op.create_index('idx_recipient_timestamp', ['recipient_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_sender_timestamp', ['sender_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('shipping_address')
        batch_op.drop_column('delivery_status')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_id'))
        batch_op.drop_index('idx_sender_timestamp')
        batch_op.drop_index('idx_recipient_timestamp')
        batch_op.drop_index('idx_recipient_read')

    # ### end Alembic commands ###
