"""Add RBAC and Inventory fields

Revision ID: 1a9a32f6f8ee
Revises: 7b0e783dfa92
Create Date: 2025-12-05 12:34:12.886299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a9a32f6f8ee'
down_revision = '7b0e783dfa92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stock_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_available', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_borrowed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_sold', sa.Integer(), nullable=True))
        batch_op.drop_column('stock')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('stock_sold')
        batch_op.drop_column('stock_borrowed')
        batch_op.drop_column('stock_available')
        batch_op.drop_column('stock_total')
        batch_op.drop_column('location')
        batch_op.drop_column('item_type')

    # ### end Alembic commands ###
