"""Added category to Book model

Revision ID: 484552f827ac
Revises: 9e2b0742cd66
Create Date: 2025-12-06 03:39:51.524529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484552f827ac'
down_revision = '9e2b0742cd66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
