"""Add socket_id to User and indexes to Message model

Revision ID: c084bb850ba0
Revises: 9f8e7d6c5b4a
Create Date: 2025-12-27 15:41:05.234430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c084bb850ba0'
down_revision = '9f8e7d6c5b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_recipient_read', ['recipient_id', 'is_read'], unique=False)
        batch_op.create_index('idx_recipient_timestamp', ['recipient_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_sender_timestamp', ['sender_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_recipient_id'), ['recipient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('socket_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('socket_id')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_recipient_id'))
        batch_op.drop_index('idx_sender_timestamp')
        batch_op.drop_index('idx_recipient_timestamp')
        batch_op.drop_index('idx_recipient_read')

    # ### end Alembic commands ###
