"""Added profile and cover photos to User

Revision ID: e58f58ff77ec
Revises: 78ed3a83b65d
Create Date: 2025-12-12 02:14:00.166467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58f58ff77ec'
down_revision = '78ed3a83b65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('cover_photo', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_photo')
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###
